{{- if .Values.rbac.create }}
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: {{ include "vault-unsealer.fullname" . }}-manager-role
  labels:
    {{- include "vault-unsealer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ops.autounseal.vault.io
  resources:
  - vaultunsealers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.autounseal.vault.io
  resources:
  - vaultunsealers/finalizers
  verbs:
  - update
- apiGroups:
  - ops.autounseal.vault.io
  resources:
  - vaultunsealers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
{{- with .Values.rbac.additionalRules }}
{{ toYaml . }}
{{- end }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: {{ include "vault-unsealer.fullname" . }}-manager-rolebinding
  labels:
    {{- include "vault-unsealer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: {{ include "vault-unsealer.fullname" . }}-manager-role
subjects:
- kind: ServiceAccount
  name: {{ include "vault-unsealer.serviceAccountName" . }}
  namespace: {{ include "vault-unsealer.namespace" . }}
---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: {{ include "vault-unsealer.fullname" . }}-leader-election-role
  namespace: {{ include "vault-unsealer.namespace" . }}
  labels:
    {{- include "vault-unsealer.labels" . | nindent 4 }}
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: {{ include "vault-unsealer.fullname" . }}-leader-election-rolebinding
  namespace: {{ include "vault-unsealer.namespace" . }}
  labels:
    {{- include "vault-unsealer.labels" . | nindent 4 }}
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: {{ include "vault-unsealer.fullname" . }}-leader-election-role
subjects:
- kind: ServiceAccount
  name: {{ include "vault-unsealer.serviceAccountName" . }}
  namespace: {{ include "vault-unsealer.namespace" . }}
{{- end }}