repos:
  - repo: https://github.com/pre-commit/pre-commit-hooks
    rev: v4.6.0
    hooks:
      - id: trailing-whitespace
      - id: end-of-file-fixer
      - id: check-yaml
        exclude: ^(helm/.*\.yaml|config/.*\.yaml|deploy/.*\.yaml|manifests/.*\.yaml|examples/.*\.yaml)$
      - id: check-added-large-files
      - id: check-case-conflict
      - id: check-merge-conflict
      - id: mixed-line-ending

  - repo: local
    hooks:
      - id: go-mod-tidy
        name: go mod tidy
        entry: go
        language: system
        args: [mod, tidy]
        files: go.mod
        pass_filenames: false

      - id: go-mod-verify
        name: go mod verify
        entry: go
        language: system
        args: [mod, verify]
        files: go.mod
        pass_filenames: false

      - id: go-fmt
        name: go fmt
        entry: gofmt
        language: system
        args: [-w]
        types: [go]

      - id: go-vet
        name: go vet
        entry: go
        language: system
        args: [vet, ./...]
        types: [go]
        pass_filenames: false

      - id: go-test-unit
        name: go test (unit tests only)
        entry: go
        language: system
        args: [test, -short, ./internal/...]
        types: [go]
        pass_filenames: false
