# the following config is for teaching kustomize where to look at when substituting namespace.
# It requires kustomize v2.1.0 or newer to work properly.
nameReference:
- kind: Service
  version: v1
  fieldSpecs:
  - kind: ValidatingAdmissionWebhook
    group: admissionregistration.k8s.io
    path: webhooks/clientConfig/service/name

namespace:
- kind: ValidatingAdmissionWebhook
  group: admissionregistration.k8s.io
  path: webhooks/clientConfig/service/namespace
  create: false

varReference:
- path: metadata/annotations/cert-manager.io~1inject-ca-from
  kind: ValidatingAdmissionWebhook
- path: metadata/annotations/cert-manager.io~1inject-ca-from
  kind: MutatingAdmissionWebhook
- path: metadata/annotations/cert-manager.io~1inject-ca-from
  kind: CustomResourceDefinition
