---
apiVersion: admissionregistration.k8s.io/v1
kind: ValidatingWebhookConfiguration
metadata:
  name: validating-webhook-configuration
webhooks:
- admissionReviewVersions:
  - v1
  clientConfig:
    service:
      name: webhook-service
      namespace: system
      path: /validate-ops-autounseal-vault-io-v1alpha1-vaultunsealer
  failurePolicy: Fail
  name: vvaultunsealer.kb.io
  rules:
  - apiGroups:
    - ops.autounseal.vault.io
    apiVersions:
    - v1alpha1
    operations:
    - CREATE
    - UPDATE
    resources:
    - vaultunsealers
  sideEffects: None
