# This rule is not used by the project vault-unsealer itself.
# It is provided to allow the cluster admin to help manage permissions for users.
#
# Grants permissions to create, update, and delete resources within the ops.autounseal.vault.io.
# This role is intended for users who need to manage these resources
# but should not control RBAC or manage permissions for others.

apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/managed-by: kustomize
  name: vaultunsealer-editor-role
rules:
- apiGroups:
  - ops.autounseal.vault.io
  resources:
  - vaultunsealers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.autounseal.vault.io
  resources:
  - vaultunsealers/status
  verbs:
  - get
