apiVersion: ops.autounseal.vault.io/v1alpha1
kind: VaultUnsealer
metadata:
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/managed-by: kustomize
  name: vaultunsealer-sample
  namespace: vault-system
spec:
  # Vault connection configuration
  vault:
    url: "https://vault.vault.svc.cluster.local:8200"
    insecureSkipVerify: false
    # Optional: Reference to CA bundle for TLS verification
    # caBundleSecretRef:
    #   name: vault-ca-cert
    #   key: ca.crt
  
  # References to secrets containing unseal keys
  unsealKeysSecretRefs:
    - name: vault-unseal-keys
      key: keys.json
    # Optional: Additional secret references for key rotation
    # - name: vault-unseal-keys-backup
    #   key: keys.txt
    #   namespace: vault-backup-system
  
  # Label selector to identify Vault pods
  vaultLabelSelector: "app.kubernetes.io/name=vault"
  
  # Unsealing mode configuration
  mode:
    ha: true  # Set to false for single-node Vault deployments
  
  # Optional: Limit number of keys to use (useful for key rotation)
  keyThreshold: 3
  
  # Optional: Custom reconciliation interval (default: 60s)
  # interval: "30s"
