apiVersion: v1
kind: ServiceAccount
metadata:
  name: vault-unsealer-controller
  namespace: vault-unsealer-system
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/component: controller
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRole
metadata:
  name: vault-unsealer-manager-role
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/component: rbac
rules:
- apiGroups:
  - ops.autounseal.vault.io
  resources:
  - vaultunsealers
  verbs:
  - create
  - delete
  - get
  - list
  - patch
  - update
  - watch
- apiGroups:
  - ops.autounseal.vault.io
  resources:
  - vaultunsealers/finalizers
  verbs:
  - update
- apiGroups:
  - ops.autounseal.vault.io
  resources:
  - vaultunsealers/status
  verbs:
  - get
  - patch
  - update
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
- apiGroups:
  - ""
  resources:
  - pods
  verbs:
  - get
  - list
  - watch
- apiGroups:
  - ""
  resources:
  - secrets
  verbs:
  - get
  - list
  - watch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: ClusterRoleBinding
metadata:
  name: vault-unsealer-manager-rolebinding
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: ClusterRole
  name: vault-unsealer-manager-role
subjects:
- kind: ServiceAccount
  name: vault-unsealer-controller
  namespace: vault-unsealer-system
---
# Leader election role
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: vault-unsealer-leader-election-role
  namespace: vault-unsealer-system
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/component: rbac
rules:
- apiGroups:
  - ""
  resources:
  - configmaps
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - coordination.k8s.io
  resources:
  - leases
  verbs:
  - get
  - list
  - watch
  - create
  - update
  - patch
  - delete
- apiGroups:
  - ""
  resources:
  - events
  verbs:
  - create
  - patch
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: vault-unsealer-leader-election-rolebinding
  namespace: vault-unsealer-system
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/component: rbac
roleRef:
  apiGroup: rbac.authorization.k8s.io
  kind: Role
  name: vault-unsealer-leader-election-role
subjects:
- kind: ServiceAccount
  name: vault-unsealer-controller
  namespace: vault-unsealer-system
