apiVersion: monitoring.coreos.com/v1
kind: ServiceMonitor
metadata:
  name: vault-unsealer-controller-metrics
  namespace: vault-unsealer-system
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/component: metrics
spec:
  endpoints:
  - path: /metrics
    port: https
    scheme: https
    bearerTokenFile: /var/run/secrets/kubernetes.io/serviceaccount/token
    tlsConfig:
      insecureSkipVerify: true
  selector:
    matchLabels:
      app.kubernetes.io/name: vault-unsealer
      app.kubernetes.io/component: metrics