apiVersion: v1
kind: Service
metadata:
  name: vault-unsealer-metrics
  namespace: vault-unsealer-system
  labels:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/component: metrics
spec:
  type: ClusterIP
  ports:
  - name: https
    port: 8443
    protocol: TCP
    targetPort: metrics
  selector:
    app.kubernetes.io/name: vault-unsealer
    app.kubernetes.io/component: controller