name: Release

on:
  push:
    tags: [ 'v*' ]
  workflow_dispatch:

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  REGISTRY: ghcr.io
  IMAGE_NAME: ${{ github.repository }}

jobs:
  determine-version:
    runs-on: ubuntu-latest
    outputs:
      version: ${{ steps.version.outputs.version }}
      is-tag: ${{ steps.version.outputs.is-tag }}
    steps:
    - name: Determine version
      id: version
      run: |
        if [[ $GITHUB_REF == refs/tags/v* ]]; then
          VERSION=${GITHUB_REF#refs/tags/v}
          echo "version=$VERSION" >> $GITHUB_OUTPUT
          echo "is-tag=true" >> $GITHUB_OUTPUT
          echo "Tag-based release: $VERSION"
        else
          echo "version=0.1.0" >> $GITHUB_OUTPUT
          echo "is-tag=false" >> $GITHUB_OUTPUT
          echo "Branch-based release: 0.1.0"
        fi

  semantic-release:
    runs-on: ubuntu-latest
    needs: determine-version
    if: false  # Disabled - only manual tags trigger releases
    permissions:
      contents: write
      packages: write
      issues: write
      pull-requests: write
    outputs:
      new-release-published: ${{ steps.semantic.outputs.new-release-published }}
      new-release-version: ${{ steps.semantic.outputs.new-release-version }}
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Node.js
      uses: actions/setup-node@v4
      with:
        node-version: '20'

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install semantic-release
      run: |
        npm install -g semantic-release
        npm install -g @semantic-release/changelog
        npm install -g @semantic-release/exec
        npm install -g @semantic-release/git
        npm install -g @semantic-release/github
        npm install -g conventional-changelog-conventionalcommits

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.12.0'

    - name: Run semantic-release
      id: semantic
      run: npx semantic-release
      env:
        GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}

  build-docker-image:
    runs-on: ubuntu-latest
    needs: [determine-version, semantic-release]
    if: always() && (needs.semantic-release.outputs.new-release-published == 'true' || needs.determine-version.outputs.is-tag == 'true')
    outputs:
      image-digest: ${{ steps.build.outputs.digest }}
      image-version: ${{ needs.determine-version.outputs.version || needs.semantic-release.outputs.new-release-version }}
    permissions:
      contents: read
      packages: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v3

    - name: Log in to Container Registry
      uses: docker/login-action@v3
      with:
        registry: ${{ env.REGISTRY }}
        username: ${{ github.actor }}
        password: ${{ secrets.GITHUB_TOKEN }}

    - name: Build and push Docker image
      id: build
      uses: docker/build-push-action@v6
      with:
        context: .
        push: true
        tags: |
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:${{ needs.determine-version.outputs.version || needs.semantic-release.outputs.new-release-version }}
          ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}:latest
        labels: |
          org.opencontainers.image.title=${{ github.repository }}
          org.opencontainers.image.description=Vault Auto-Unseal Operator
          org.opencontainers.image.version=${{ needs.determine-version.outputs.version || needs.semantic-release.outputs.new-release-version }}
          org.opencontainers.image.source=${{ github.server_url }}/${{ github.repository }}
          org.opencontainers.image.revision=${{ github.sha }}
        cache-from: type=gha
        cache-to: type=gha,mode=max
        platforms: linux/amd64,linux/arm64

  package-and-release:
    runs-on: ubuntu-latest
    needs: [determine-version, semantic-release, build-docker-image]
    if: always() && needs.build-docker-image.result == 'success'
    permissions:
      contents: write
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        fetch-depth: 0

    - name: Set up Go
      uses: actions/setup-go@v5
      with:
        go-version: '1.21'
        cache: true

    - name: Install Helm
      uses: azure/setup-helm@v4
      with:
        version: '3.12.0'

    - name: Generate CRDs and package Helm chart
      run: |
        make release VERSION=${{ needs.build-docker-image.outputs.image-version }}

    - name: Upload release artifacts
      uses: softprops/action-gh-release@v2
      with:
        tag_name: v${{ needs.build-docker-image.outputs.image-version }}
        files: |
          release/*.tgz
          release/*.yaml
          release/install.sh
        generate_release_notes: false

  security-scan:
    runs-on: ubuntu-latest
    needs: build-docker-image
    if: always() && needs.build-docker-image.result == 'success'
    permissions:
      contents: read
      security-events: write
    steps:
    - name: Run Trivy vulnerability scanner
      uses: aquasecurity/trivy-action@master
      with:
        image-ref: ${{ env.REGISTRY }}/${{ env.IMAGE_NAME }}@${{ needs.build-docker-image.outputs.image-digest }}
        format: 'sarif'
        output: 'trivy-results.sarif'

    - name: Upload Trivy scan results to GitHub Security tab
      uses: github/codeql-action/upload-sarif@v3
      if: always()
      with:
        sarif_file: 'trivy-results.sarif'

  trigger-helm-repo:
    runs-on: ubuntu-latest
    needs: [build-docker-image, package-and-release]
    if: always() && needs.package-and-release.result == 'success'
    steps:
    - name: Trigger Helm repository update
      uses: actions/github-script@v7
      with:
        script: |
          github.rest.actions.createWorkflowDispatch({
            owner: context.repo.owner,
            repo: context.repo.repo,
            workflow_id: 'helm-repo.yaml'
          })
